### PR TITLE
puppetlabs/concat: Allow 8.x & 9.x

### PR DESCRIPTION
**Pull request by bastelfreak**

### CODE REVIEW

**Review by smortex — APPROVED** [review]

**Comment by smortex** [comment]
I have the same Puppet 8 CI failure on a project (not a Vox Pupuli one) and still have not found the root cause… :-(

**Comment by bastelfreak** [comment]
@smortex https://github.com/puppetlabs/puppet/pull/9082

**Comment by smortex** [comment]
Ah yes, I saw the issue vanished a few weeks ago.

**Review by smortex — APPROVED** [review]
LGTM!

I think #289 must be updated to point to the correct commit in this PR?

**Comment by bastelfreak** [comment]
@smortex I rebased it and merged the other PR first, it's fine now.

**Pull request merged**
