### PR TITLE
Support for metric argument in vrrp_instancevirtual_routes

### PR DESCRIPTION
**Pull request by KrzysztofHajdamowicz**
Hi,

I was building keepalived cluster and I suffered a bit due to lack of metric support.
I've added this feature and I want to merge it with upstream.

### CODE REVIEW

**Comment by arioch** [comment]
Hi, could you rebase onto master and fix the tests please?

**Comment by arioch** [comment]
Hi, could you rebase this onto master and fix the tests please?

**Comment by KrzysztofHajdamowicz** [comment]
Hi, fixed. Should be working right now :)

**Comment by bastelfreak** [comment]
Thanks for the PR!

**Pull request merged**
