### PR TITLE
Replace all occurrences of illegal chars in the name var

### PR DESCRIPTION
**Pull request by gerases**

### CODE REVIEW

**Comment by gerases** [comment]
I'm not sure of the reason for the failed builds. It's not me right?

**Comment by smortex** [comment]
Debian 9 and Ubuntu 16.04 are EOL, you can ignore failures (if you want, you can rebase on top of master to integrate their removal):

From your working directory:

```
git fetch origin         # Download the latest code we have here
git rebase origin/master # Move your commits on top of the main branch
git push -f              # Send the changes (-f is required because you re-wrote history)
```

**Review by smortex — APPROVED** [review]
That looks reasonable.

**Comment by zilchms** [comment]
Hey @gerases,
can you rebase this and fix the merge conflicts? :) If the CI passes then, I can merge it

**Comment by gerases** [comment]
@zilchms , done, let me know if you need me to do anything else

**Pull request merged**
