### PR TITLE
virtual_ipaddress should be on vrrp interface if use_vmac is set

### PR DESCRIPTION
**Pull request by saz**
Virtual ip addresses should be setup on vrrp interface if use_vmac is set

### CODE REVIEW

**Comment by saz** [comment]
I've just realised, that `virtual_ipaddress_excluded` should be handled the same way. I'll update this PR asap

**Comment by saz** [comment]
If tests are successful, this PR should be complete

**Comment by saz** [comment]
The failing test seems to be something else.

**Comment by saz** [comment]
Any news on this one?

**Comment by regiohelden-dev** [comment]
Thanks @bastelfreak

**Comment by saz** [comment]
Thanks @bastelfreak

**Pull request merged**
